export type { ChunkStrategy, Document, Chunk, IndexedChunk, Index, FixedOptions } from './types.ts';
export { chunkFixed, chunkStructural, chunkDocument } from './chunkers.ts';
export type { ChunkOptions } from './chunkers.ts';
export { cosineSimilarity, topK } from './cosine.ts';
export type { ScoredChunk } from './cosine.ts';
export { JsonIndexStore } from './index-store.ts';
export type { IndexStore } from './index-store.ts';
export { buildIndex } from './index-builder.ts';
export type { BuildOptions, EmbedFn } from './index-builder.ts';
export { computeStats } from './stats.ts';
export type { StrategyStats } from './stats.ts';
export { isTextFile, loadLocalDocuments } from './sources/local.ts';
export type { LocalIo } from './sources/local.ts';
export { htmlToText, extractTitle, extractLinks, crawlWeb } from './sources/web.ts';
export type { FetchText } from './sources/web.ts';
export { isGithubUrl, githubTarballUrl } from './sources/github.ts';
export { detectSource, loadDocuments } from './sources/resolve.ts';
export type { SourceKind, SourceLoaders } from './sources/resolve.ts';
export { nodeLocalIo, nodeLoaders } from './sources/node-io.ts';
